### ISSUE TITLE
Some problems since recent update

### ISSUE THREAD

**Issue by lgalke** [Konfekt/vim-sentence-chopper#1]
Hi thanks for making this. I used a custom regex-based split as formatprg before and wasn't aware of latexident. My version was quite naive and could deal poorly with sentences inside comments.

Anyways, since some recent update, I encounter some problems.

`vipgw` -> chops sentences as intended. however `vipgw` reverts back to put everything on one line. Even worse, `gwip` only puts everything on one line for me and does not actually chop if applied to full. Also `gww` or `gwgw` do not split anymore.

#### output of `:verbose map gw`

```
x  gw            <Plug>(ChopSentences)
        Last set from ~/dotfiles/vim/.vim/plugged/vim-sentence-chopper/plugin/sentences.vim line 53
n  gw            <Plug>(ChopSentences)
        Last set from ~/dotfiles/vim/.vim/plugged/vim-sentence-chopper/plugin/sentences.vim line 50
```

Also, since these problems came up, I get prompted to hit Enter after `gw`. Could it be that latexindent exited with error?

#### latexindent version

```
[nephthys al-folio* master] > which latexindent
/usr/bin/latexindent
[nephthys al-folio* master] > latexindent --version
3.5.3, 2018-10-13
```

edit for the record: I observed these problems in a document with markdown filetype, textwidth was set to 80.

I'd be grateful for any help. Let me know if you need more info

**Comment by Konfekt** [comment]
I am using latexindent 3.6 from May, if  you could update, that might help. At least I cannot reproduce

> vipgw -> chops sentences as intended. however vipgw reverts back to put everything on one line. Even worse, gwip only puts everything on one line for me and does not actually chop if applied to full. Also gww or gwgw do not split anymore.

There were few changes to this plug-in but error handling was added in https://github.com/Konfekt/vim-sentence-chopper/commit/4df704b3105f47dc55bd0f1bbe9f380ccd5ab221 
If `latexindent` exists with an error, the message can be read by redo `<c-r>` or `:redo`.

Did you try `let g:latexindent = 0` in the meanwhile? It uses also a custom regex-based split. Perhaps you can merge yours in. But true, it probably does not add comment markers.

To understand better what happened, 

> since some recent update

is too vague. Ideally, you could bisect the offending update.

**Comment by lgalke** [comment]
`:redo` or `<C-r>` show nothing but 'Already at newest change'.

With `g:latexindent = 0`, visual selection + `gw` works as intended (also it does not wrongly reverse formatting). `gwip` yields E20: `mark not set` `while processing sentence#chop` for the blink of an eye.

I haven't found time to bisect yet, maybe tonight.

**Comment by lgalke** [comment]
Updates: I noticed that another plugin `pandoc` has been causing (most of) the trouble. It does set `equalprg`, which does not get reverted when I change the filetype back to plain `markdown`. When I manually reset `equalprg=`, the built-in formatting works well. Still the issue with latexindent requiring one Enter key press remains, but apart from that, it also works as intended *as long as equalprg is empty*. To summarize current state:

- with latexindent, `<cr>` key press is required after execution of the external program
- both with and without latexindent, the behaviour seems to depend on equalprg; it works when `equalprg` is empty
- might not be caused by recent update, I'm sorry. Might be the problem that I recently switched pandoc highlighting on for some specific markdown document

**Comment by Konfekt** [comment]
I could not reproduce because I had `let g:pandoc#formatting#equalprg=''` set a long time ago. But the latest two commits should resolve this issue independently.

**Comment by Konfekt** [comment]
Thanks for having pointed out this issue!

**Comment by lgalke** [comment]
Thanks for the rapid fix. For some reason, now the issue with the <Enter> keypress seems to be resolved, too. Using formatprg may be also a bit cleaner than equalprg (semantically) ;)

If you're curious, you can find [my approach here](https://gitlab.com/lgalke/dotfiles/blob/master/vim/.vim/autoload/sentence.vim).

I basically put the crucial code into a function such that I can

```
au FileType text,markdown,tex setlocal formatexpr=sentence#format()
```

and then use standard gq in these documents.

Anyways, I also appreciate your unobstrusive way that does not require setting any options.

**Comment by Konfekt** [comment]
Is the main difference that  your format function keep comments as-is (whereas I simply desist from handling markup code)?

**Comment by lgalke** [comment]
The first version was very similar to yours. The second version that I made just yesterday night is now robust to comments. RIght now it does simply "ignore" them. Well it places them on single lines.
But with the more verbose code of reading the buffer via `getline` and then later replacing the text is much more flexible than the single regexp before. I'm thinking just now whether I just add sentence splitting for comments aswell and insert comment marker before each inserted comment line.
