### ISSUE TITLE
Spaces appended when splitting

### ISSUE THREAD

**Issue by joelostblom** [Konfekt/vim-sentence-chopper#2]
Thanks for making this plugin! I am trilling working with semantic line breaks in markdown and your work is making that much easier!

One thing I have noticed is that when I split a paragraph into semantic line breaks, there is a blank space appended to each line. In markdown, this is unnecessary since single newline characters will be interpreted as spaces. Would it be possible to suppress this behavior, possibly through an added option?

I am running with `let g:latexindent = 0`.

**Comment by Konfekt** [comment]
Thanks for pointing the trailing whitespaces out. I adapted the regular expression used when `!g:latexindent` and hopefully everything keeps working. Please give it a try and check back.

**Comment by joelostblom** [comment]
Works perfectly, thanks for the quick fix!
