### ISSUE TITLE
whole buffer ChopSentences: would be nice to preserve the cursor location

### ISSUE THREAD

**Issue by hudson-ayers** [Konfekt/vim-sentence-chopper#6]
Currently, running :ChopSentences to format an entire file moves the cursor to the beginning of the file -- it would be nice if instead the position of the cursor could be preserved.

**Comment by hudson-ayers** [comment]
For now, I am using the following in my .vimrc as an alternative:

```vim
" On its own, ChopSentences does not preserve window/cursor location
func! FormatLatex()
  let l:winview = winsaveview()
  :ChopSentences
  call winrestview(l:winview)
endf
```

**Comment by Konfekt** [comment]
Yes, that's a more advanced way. `:help restore-position` offers the elementary alternative

```
Restoring the cursor position				*restore-position*

Sometimes you want to write a mapping that makes a change somewhere in the
file and restores the cursor position, without scrolling the text.  For
example, to change the date mark in a file: >
   :map <F2> msHmtgg/Last [cC]hange:\s*/e+1<CR>"_D"=strftime("%Y %b %d")<CR>p'tzt`s

Breaking up saving the position:
	ms	store cursor position in the 's' mark
	H	go to the first line in the window
	mt	store this position in the 't' mark

Breaking up restoring the position:
	't	go to the line previously at the top of the window
	zt	scroll to move this line to the top of the window
	`s	jump to the original position of the cursor

For something more advanced see |winsaveview()| and |winrestview()|.
```

I would use `g`` to keep the jump list intact, though.

`:help winsaveview` mentions:

```
		This is useful if you have a mapping that jumps around in the
		buffer and you want to go back to the original view.
		This does not save fold information.  Use the 'foldenable'
		option to temporarily switch off folding, so that folds are
		not opened when moving around. This may have side effects.
```

I am not sure which is more appropriate.
Overriding and restoring a mark feels kind of a hack, but `winsaveview` also like a bit of an overkill.

**Comment by hudson-ayers** [comment]
`winsaveview` has been working quite well for me in practice

**Comment by Konfekt** [comment]
Hello,

there was already set a mark to restore the cursor position.
I replaced the commands by the `winsave/restview` commands

```vim
" autoload/sentences.vim (lines 40-58)
function! sentences#chop(...) abort
  " normal! m`
  let l:winview = winsaveview()

  if a:0 == 2
    " visual mode
    let open  = a:1
    let close = a:2
  else
    " normal mode
    let open  = "'["
    let close = "']"
  endif

  call s:chop(open, close)

  " normal! g``
  call winrestview(l:winview)
endfunction
```

but filling a buffer with `lorem ipsum ...` and calling `gwip` still did not restore the cursor line if the cursor was not on the first line of the paragraph.
Also setting manually a mark will fail to restore it.
This seems to hold for all operator commands involving lines before the cursor position.

**Comment by hudson-ayers** [comment]
Hmm, my approach is mostly useful for when formatting the entire buffer (e.g. just `:ChopSentences`) what I find is that winsaveview will not always perfectly restore the cursor position within the paragraph but it is usually close, and that is much better than the cursor being moved all the way to the top of the file.

You are right that when just formatting a single paragraph this is not that helpful

**Comment by Konfekt** [comment]
Thank you for pointing out this issue. There was a flaw that went unnoticed. The cursor line should already have been kept respectively restored, but the modifier`keepjumps` to that end was missing at one place. It should be fine now
