### ISSUE TITLE
Line after first comma becomes indented

### ISSUE THREAD

**Issue by hanschen** [Konfekt/vim-sentence-chopper#9]
I have:

```vim
let g:punctuation_marks = ",?!"
```

When I run `gww` on the following text (no filetype set):

```
this, is, a test
```

it becomes

```
this,
    is,
    a test
```

instead of the expected

```
this,
is,
a test
```

The indentation seems to depend on `shiftwidth`. I can reproduce with both vim 9.1 and neovim v0.10.0.

Any ideas what causes this?

**Comment by Konfekt** [comment]
In view of 

```vim
" autoload/sentences.vim (lines 132-135)
let equalprg = &l:equalprg
let equalprg = ''
exe 'silent keepjumps normal! ' . o . '=' . c
let &l:equalprg = equalprg
```

and

```
'equalprg' 'ep'		string	(default "")
			global or local to buffer |global-local|
	External program to use for "=" command.  When this option is empty
	the internal formatting functions are used; either 'lisp', 'cindent'
	or 'indentexpr'.  When Vim was compiled without internal formatting,
	the "indent" program is used.
```

I think you need to share these mentioned options.

**Comment by hanschen** [comment]
Aha - thank you for the fast answer. Thanks to it, I was able to find a workaround:
```vim
:set cinoptions+=+0
```

Source: https://stackoverflow.com/a/21413701

I hope it'll work well if I use this option for text files. Feel free to close this issue if you want.

---

For more information:

```vim
:set equalprg?
equalprg=
:set lisp?
nolisp
:set cindent?
nocindent
:set indentexpr?
indentexpr=
```

(i.e., the default values).

Pressing `==` on the second line does indeed indent it. If I put the cursor on the first comma and press `o` or `Enter` in insert mode, it doesn't indent. If I `:set lisp`, it doesn't indent.

**Comment by Konfekt** [comment]
Thank you for documenting this work around; I suggest it now as well in this plug-in's docs.
